[pg-primary]
192.168.4.117 ansible_user=${SSH_USER:-cbwinslow}

[pg:children]
pg-primary

[all:vars]
pg_cluster=mycluster
pg_version=16
pg_data=/var/lib/postgresql/16/main
pg_listen=0.0.0.0
pg_extensions=vector,pg_trgm

